export const FETCH_NEWS = 'FETCH_NEWS';

export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_FAILED = 'FETCH_FAILED';

export const FETCH_SINGLE_NEW = 'FETCH_SINGLE_NEW';

export const FETCH_SINGLE_NEW_SUCCEEDED = 'FETCH_SINGLE_NEW_SUCCEEDED';
export const FETCH_SINGLE_NEW_FAILED = 'FETCH_SINGLE_NEW_FAILED';